### ISSUE TITLE
Please add an open source LICENSE

### ISSUE THREAD

**Issue by gpshead** [humu/heapprof#14]
This code lacks any license.  Please apply an open source license to everything and add a LICENSE file.  (otherwise nobody can legally use it)

**Comment by zunger-humu** [comment]
D'oh! It has a license (MIT), but it's linked in a weird way from the docs directory. I'll add a LICENSE.md in the root directory as well.

**Comment by zunger-humu** [comment]
@gpshead , do you know where the spec is defined for where to stick licenses, codes of conduct, etc., so that standard tools can find them? I can't find this anywhere in the formal docs. (Trying to figure out if, e.g., LICENSE.md is acceptable or only LICENSE, if there's a standard name for codes of conduct, and so on)

**Comment by gpshead** [comment]
No idea if there's a _spec_, but generally a LICENSE (optionally .txt or .md) file in the top directory counts and is what I see on most repos.  For code of conducts I'm used to seeing that done similarly as a top level CODE_OF_CONDUCT.md for Python related projects that carry them.

I suspect the top level license file is what makes github show the license icon on the index page.  https://help.github.com/en/articles/licensing-a-repository

**Comment by zunger-humu** [comment]
Close enough. :) PR: https://github.com/humu/heapprof/pull/17

**Comment by zunger-humu** [comment]
Fix submitted and will be released in 1.0.1.
